### PR TITLE
Added CentOS 8 support in parameters

### PR DESCRIPTION
**Pull request by aursu**

### CODE REVIEW

**Comment by floSoX** [comment]
Thank you for your contribution.
Could you add some tests please?

**Comment by aursu** [comment]
> Thank you for your contribution.
> Could you add some tests please?

Of course - just give me some time. I will push them
Thank you

**Comment by aursu** [comment]
Hello, @floSoX 

I was not able to run tests on PDK 1.18. Looks like it has never version of Facter which produces major versions for Amazon Linux as 2016/2017/2018 (not '2' and '4'). Therefore I've added Docker compose settings for PDK 1.10 (earliest available for PDK).

Actually I've added section (or context) for centos-8-x86_64 that is 30+ unit tests for this platform

Also I've fixed one of the current unit test (added misses custom fact from firewall module)

If you do not need docker settings (Dockerfile & docker-compose.yml) - just let me know I will remove both. Honestly I forgot to exclude them from commit

Thank you

**Comment by aursu** [comment]
Closed as merge request has been submitted from branch 'master' of my fork.

While these MRs not merged I want to use my fork in production. 
All changes from this MR are available in https://github.com/solution-libre/puppet-monit/pull/19

Sorry for inconvenience

**Pull request closed without merging**
